name: Static Analysis
on:
  pull_request:
    paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ github.actor }}"
     # - run: |
     #     rhysd/actionlint:latest
